### ISSUE TITLE
Add snappy compression to RLPx (EIP-706)

### ISSUE THREAD

**Issue by zah** [status-im/nim-eth-p2p#3]
Add support for Snappy compression in DevP2P as specified in:
* https://github.com/ethereum/EIPs/blob/master/EIPS/eip-706.md

The implementation will involve modifying the procs `rlpxConnect` (for the negotiation step), `recvMsg` and `send` from the `rlpx.nim` module. 

Initially, the feature should be implemented behind a compilation `define` flag.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xc22a32cd7d5d53395fff86d5613ae4f228775be15feaf5d5e162738eb5464fe8](https://etherscan.io/tx/0xc22a32cd7d5d53395fff86d5613ae4f228775be15feaf5d5e162738eb5464fe8)

**Comment by pablanopete** [comment]
@data-man could you refer to this commit as "Fixes: XX" for the bounty to pick it up? Are you still working on this?

**Comment by data-man** [comment]
@pablanopete 
Sorry, I missed your message. :(
> Are you still working on this?

Yes, I'll continue work on this very soon.

@kishansagathiya 
Do you plan implement Snappy on pure Nim?

**Comment by zah** [comment]
Yes, this issue is still relevant. It can be migrated to Gitcoin or handled OOB when somebody delivers a working solution.

**Comment by zah** [comment]
For the [implementation of this bounty](https://github.com/status-im/nim-eth-p2p/pull/50) and the creation of the [nim-snappy](https://github.com/jangko/snappy/) library, a reward of 600 USD have been paid out to @jangko:

https://etherscan.io/tx/0xf9afc0334aa814ffd95beb198a1cf4740843588a1bee92c58f3ab7d73c023b17
