### ISSUE TITLE
Cannot install to nim 0.18.0

### ISSUE THREAD

**Issue by namuyan** [status-im/nim-eth-p2p#30]
I use windows10 64bits
```bash
(base) C:\Users\name>nimble install --verbose eth_p2p
    Reading official package list
Downloading https://github.com/status-im/nim-eth-p2p using git
    Setting Nim stdlib prefix to C:\Users\name\AppData\Local\nim-0.18.0
    Setting Nim stdlib path to C:\Users\name\AppData\Local\nim-0.18.0\lib
  Verifying dependencies for eth_p2p@1.0.0
     Error: Unsatisfied dependency: nim (> 0.18.0)
```
Cannot install by nim version error.
But nim is newest. Please help me.

**Comment by data-man** [comment]
> nim (> 0.18.0)

You need to use Nim-devel (currently it's version 0.18.1).

**Comment by namuyan** [comment]
Thank you for comment.
This lib is under hard development? and not recommend to use for general?

**Comment by arnetheduck** [comment]
Early stages and heavy development - it's pushing the boundaries of the nim compiler as well, hence the need for a devel version.. reopen if it still doesn't work after using a fresh nim
