### ISSUE TITLE
Make the library gcsafe / ok to use with --threads:on

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-eth-p2p#60]
For a use case like stratus, running the async loop and gui in separate threads would be a good solution..

A way to go about this is to fix gc-safety here, then switch `--threads:on` for all our projects, as a part of development requirements.

**Comment by arnetheduck** [comment]
well, I couldn't switch threads on for it - is there anyway to force gcsafety instead? otherwise, do we have links to bugs so we can track them specifically?

**Comment by cheatfate** [comment]
I dont think library is GC safe and i never seen bugs in Nim gcsafe analysis.
https://github.com/status-im/nim-eth-p2p/blob/master/eth_p2p/rlpx.nim#L30-L33

**Comment by cheatfate** [comment]
It looks like you are trying to cheat Nim gcsafe analysis... We could also ask @Araq to review it safety.

**Comment by zah** [comment]
I'm cheating the `gcsafe` analysis, but in a safe way. All globals represent something like RTTI data that is populated at the start of the program and stays read-only afterwards. The bug I've seen is that Nim is not always taking into account my overrides in certain situations involving generic functions.

**Comment by Araq** [comment]
"read only afterwards" is usually not good enough, ``heapLocation = readOnlyAfterwards(tm)`` messes with the refcount without atomic protections.

**Comment by arnetheduck** [comment]
buggy as it may be, I trust the compiler over human judgement - specially over time. Even if your code originally is safe, modifications to it may not be - but the override stays in place. We've discussed these before and it would be a lot nicer if they were initialized statically so that we could trust them.

**Comment by zah** [comment]
`threadvar` is not suitable for the RTTI-like data. It is suitable only for the dispatcher cache, but I've removed the cache altogether for now.

**Comment by cheatfate** [comment]
https://github.com/status-im/nim-eth-p2p/commit/bf1147291b4d79fb4ce4695aa22e6ccad15be34a#diff-2d3dee6ad6d3f0b80925ec1de5c53319R103
I dont think it is safe to store `string` inside of `ptr` object.

**Comment by arnetheduck** [comment]
this needs to stay open until the library actually can be used with `--threads:on`

**Comment by zah** [comment]
Right @cheatfate, good catch. I've modified the code to put the `ProtocolInfo` objects in regular non-allocated globals which will make sure they stay alive.

@arnetheduck, all tests compile and run now with `--treads:on`.

**Comment by stefantalpalaru** [comment]
It's still not GC-safe on Windows because of some Windows-specific terminal handling: https://ci.appveyor.com/project/jarradh/nim-eth-p2p/builds/21405943

**Comment by stefantalpalaru** [comment]
Different error when compiling Nimbus on a 64-bit Windows 10 instance:
```
..\vendor\repos\status-im\nim-eth-p2p\eth_p2p\rlpx.nim(1104, 13) template/generic instantiation from here
..\vendor\repos\status-im\nim-eth-p2p\eth_p2p\rlpx.nim(899, 18) Error: type mismatch: got <ptr ProtocolInfoObj, int literal(0), string, proc (msgSender: Peer, _: int, data: Rlp): Future[system.void]{.gcsafe, locks: <unknown>.}, proc (msg: pointer): string{.noSideEffect, gcsafe, locks: 0.}, proc (msg: pointer, future: FutureBase){.locks: <unknown>.}, proc (msgData: Rlp, future: FutureBase){.gcsafe, locks: <unknown>.}>
but expected one of:
proc registerMsg(protocol: ProtocolInfo; id: int; name: string; thunk: MessageHandler;
                printer: MessageContentPrinter; requestResolver: RequestResolver;
                nextMsgResolver: NextMsgResolver)
  first type mismatch at position: 6
  required type: RequestResolver
  but expression 'requestResolver' is of type: proc (msg: pointer, future: FutureBase){.locks: <unknown>.}
  This expression is not GC-safe. Annotate the proc with {.gcsafe.} to get extended error information.

expression: registerMsg(devp2pProtocol, 0, "hello", hello_thunk, messagePrinter, requestResolver,
            nextMsgResolver)
```
and another one compiling Nimbus on Linux:
```
../vendor/repos/status-im/nim-eth-p2p/eth_p2p/blockchain_sync.nim(332, 22) Error: type mismatch: got <proc (p: Peer){.closure, locks: <unknown>.}> but expected 'proc (p: Peer){.closure, gcsafe.}'
```

**Comment by zah** [comment]
The Linux build of Nimbus works for me after the following commit: https://github.com/status-im/nim-eth-p2p/commit/0300ebdb14f169c13e4444f9e98c8b8d0b4842a1

Based on the Windows error message, I also tried to push another fix here )https://github.com/status-im/nim-eth-p2p/commit/53e98faa74ce3f9e690fc985e56d18cf76b67b42), but haven't got a change to test it yet. As a minimum, it should change the error message.

As you can infer from the commits above, fixing such issues is usually just a matter of adding the `gcsafe` pragma in the right place. The compiler analysis can't figure out the correct `gcsafe` status sometimes.

**Comment by arnetheduck** [comment]
thanks!
